### ISSUE TITLE
Problem with split selection

### ISSUE THREAD

**Issue by halolord01** [xavi-/sublime-selectuntil#11]
Split selection is a great command, but I always seem to have a small problem with it. Whenever I select a block of text, and use split select, I always get an additional cursor where the cursor was before I split the selection. I'll try to demonstrate what I mean, but the formatting ma be off
Lotsof[5].text     With the cursor at the end of ints before splitting the selection. After splitting the selection
Lotsof[5].text     and using  .  as the divider, and then using the left arrow key, cursors appear to the left
Lotsof[5].ints    off all the periods, but there is still one at the end of ints. This is very annoying, and it
                       makes using the command very difficult. Some sort of fix would be amazing, thanks again for the great package!

**Comment by xavi-** [comment]
Hello,

I'm sorry, I don't quite understand.  Which split selection commend are you referring to?

**Comment by halolord01** [comment]
Hm, sorry about that, I think I posted in the wrong package page.

**Comment by xavi-** [comment]
Haha it's okay.  Out of curiosity what's the name of the package?

## 

Typed with thumbs and sent with love from Boomerang

**Comment by halolord01** [comment]
Multi edit utils. It has a bunch of great features, I just can't get one to work too well.

**Comment by xavi-** [comment]
That package looks pretty great.  Thanks for mentioning.
