### ISSUE TITLE
Toggle to include or exclude the search term in the selection

### ISSUE THREAD

**Issue by FichteFoll** [xavi-/sublime-selectuntil#17]
In many circumstances, I only want to select _until_ a certain character but SelectUntil always includes the search term in the final selection. I would love to have a keyboard toggle for this. Similarly, using `"expand": false` currently has the exact opposite behavior where the caret is alwaysmoved to _after_ the search pattern.

I can imagine a context-specific binding like `alt+space` or `alt+enter` to be used for this, that will only trigger when the selectuntil input panel is open.

**Comment by FichteFoll** [comment]
By the way, I can implement a few features mentioned in other issues and pull requests, as long as I find the time for it.
If you fear of not having the time to maintain this package anymore, you can migrate it to the https://github.com/SublimeText/ org with lots of plugin devs that can take over unmaintained packages.

There is also a pull request to a competing package that brings very interesting functionality: https://github.com/JonasPf/JumpTo/pull/7

Edit: You should add an actual license to your project before that, though. Just a reference is usually not enough.

**Comment by erfanimani** [comment]
+1, excluding search term would be super useful.

**Comment by Asuza** [comment]
@xavi- this feature would be nice. I was expecting this behavior by default, based on the package name. As-is, I expect the package would be named "SelectIncluding".

**Comment by FichteFoll** [comment]
Closing, since the repository appears unmaintained and the PR I referenced earlier has been merged. I switched to that package a while ago and am not interested in a fix here anymore.
