### ISSUE TITLE
SelectUntil not present in the Preferences → Package Settings menu

### ISSUE THREAD

**Issue by galli-a** [xavi-/sublime-selectuntil#5]
There is no way to access the settings via ST menu, neither default nor user settings.
The issue is that the default OS X keybinding is different from that detailed here on github, so to find the right keybinding I tried to access the settings from the menu, but to no avail.

ST3 build 3041

**Comment by xavi-** [comment]
Sorry my mistake.  I added some clarifying text to the README and added SelectUntil to the Main menu under "Selection".

Thanks for the heads up.
